# Generated by Django 2.2.7 on 2019-11-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mypodcasts', '0015_podcast_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsPodcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypodcasts.Podcast')),
            ],
        ),
    ]
