# Generated by Django 2.2.7 on 2019-11-29 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcasts', '0015_podcast_language'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewspodcast',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='mypodcasts.Podcast'),
        ),
        migrations.CreateModel(
            name='ViewsEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='mypodcasts.Episode')),
            ],
        ),
    ]
