# Generated by Django 2.2 on 2019-06-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chaneld',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
