# Generated by Django 2.2 on 2019-06-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20190601_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='chaneld',
            new_name='channelid',
        ),
    ]
