# Generated by Django 2.2 on 2019-06-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20190601_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='channelid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
