# Generated by Django 2.2 on 2019-06-14 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mypodcasts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypodcasts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('video_id', models.CharField(max_length=64)),
                ('audio_file', models.FileField(blank=True, upload_to=mypodcasts.models.user_directory_path_audio)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mypodcasts.models.user_directory_path)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypodcasts.Podcast')),
            ],
        ),
    ]
