# Generated by Django 2.2 on 2019-06-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcasts', '0002_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
