# Generated by Django 2.2 on 2019-06-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcasts', '0003_auto_20190617_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='mypodcasts.Podcast'),
        ),
    ]
