# Generated by Django 2.2 on 2019-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcasts', '0004_auto_20190617_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='author',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
