# Generated by Django 2.2 on 2019-06-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcasts', '0007_podcast_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
