# Generated by Django 2.2.7 on 2019-11-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcasts', '0011_auto_20191128_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='categories',
            field=models.ManyToManyField(blank=True, to='category.SubCategory'),
        ),
    ]
