# Generated by Django 2.2.7 on 2019-11-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcasts', '0013_remove_podcast_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='language',
        ),
    ]
